In [37]:
import pandas as pd
import numpy as np
tqid = [0, 1, 2]
y1 = [1, 2, 4]
y2 = [2, 4, 6]
y3 = [4, 8, 8]
y4 = [2, 4, 6]
dfa = pd.DataFrame({"qid": tqid, "y1" : y1, "y2" : y2, "y3" : y3, "y4" : y4})
z1 = [2, 3, 4]
z2 = [2, 3, 6]
z3 = [2, 4, 8]
z4 = [2, 5, 6]
dfb = pd.DataFrame({"qid": tqid, "y1" : z1, "y2" : z2, "y3" : z3, "y4" : z4})


In [94]:
from sklearn.preprocessing import StandardScaler
def get_scaled_from_df(df):
    distances = np.array(df.values[:, 1:], dtype = float)
    distances = distances.T
    scaler = StandardScaler()
    scaler.fit(distances)
    return scaler.transform(distances).T

def get_averaging_from_df(dfa, dfb):
    return (get_scaled_from_df(dfa) + get_scaled_from_df(dfb)) / 2

def scale_dfs(dfa, dfb):
    print(dfa.values[:, 0])
    return pd.DataFrame(columns = dfa.columns.values, data=np.hstack([np.array([dfa.values[:, 0]], dtype=str).T, get_averaging_from_df(dfa, dfb)]))

In [95]:
print(get_scaled_from_df(dfa))
print(get_scaled_from_df(dfb))

get_averaging_from_df(dfa, dfb)

[[-1.14707867 -0.22941573  1.60591014 -0.22941573]
 [-1.14707867 -0.22941573  1.60591014 -0.22941573]
 [-1.41421356  0.          1.41421356  0.        ]]
[[ 0.          0.          0.          0.        ]
 [-0.90453403 -0.90453403  0.30151134  1.50755672]
 [-1.41421356  0.          1.41421356  0.        ]]


array([[-0.57353933, -0.11470787,  0.80295507, -0.11470787],
       [-1.02580635, -0.56697488,  0.95371074,  0.63907049],
       [-1.41421356,  0.        ,  1.41421356,  0.        ]])